### ISSUE TITLE
Problem with regex

### ISSUE THREAD

**Issue by nikhil-pandey** [nikhil-pandey/worldlink-ticket#3]
Running test at Server#4098
Ping: 361.107 ms
Download: 9.92 Mbit/s
Upload: 7.50 Mbit/s

Traceback (most recent call last):
  File "./main.py", line 70, in <module>
    test()
  File "./main.py", line 54, in test
    speed = speedtest(server)
  File "./main.py", line 38, in speedtest
    data = [ server, float(fSpeed.group(1)), float(fSpeed.group(2)), float(fSpeed.group(3)), date]
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by nikhil-pandey** [comment]
Fixed by 81d7455372a6083ddf6d67665172702623dd5ec5
